CREATE TABLE IF NOT EXISTS users
(
    id CHARACTER VARYING(30) NOT NULL,
    username CHARACTER VARYING(32) NOT NULL,
    password CHARACTER VARYING(100) NOT NULL,
    name CHARACTER VARYING(100) NOT NULL DEFAULT '',
    dob CHARACTER VARYING(10) NOT NULL DEFAULT '',
    gender SMALLINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    deleted_at BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
    UNIQUE (username)
);